# Generated by Django 5.0.3 on 2024-06-15 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='collaborators',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='image1',
            field=models.ImageField(default=False, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='image2',
            field=models.ImageField(default=False, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='text',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='video1',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='video2',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
