# Generated by Django 5.0.3 on 2024-06-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0003_alter_timecapsule_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='is_sealed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
