# Generated by Django 4.2.2 on 2024-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0004_timecapsule_is_sealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
    ]
