# Generated by Django 4.2.2 on 2024-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0005_timecapsule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
