# Generated by Django 4.2.2 on 2024-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0006_alter_timecapsule_image1_alter_timecapsule_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
