# Generated by Django 4.2.2 on 2024-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0007_alter_timecapsule_image1_alter_timecapsule_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='force_open_pass',
            field=models.TextField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
