# Generated by Django 4.2.2 on 2024-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0011_alter_timecapsule_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
